# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AlanXue's Blog
email: 836106158@qq.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog for Alan Xue. And it hasn't been completed.
baseurl: /AlanXue1997.github.io
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: XueZhonghao
github_username:  AlanXue1997

# Build settings
markdown: kramdown
